# Generated by Django 5.1.2 on 2024-11-11 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0008_rooms_slot_available_alter_roomtransfer_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='bank',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='slot_available',
            field=models.IntegerField(default=2),
        ),
    ]
