# Generated by Django 5.1.2 on 2024-11-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0010_revenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenue',
            name='roomrevenue',
            field=models.IntegerField(default=0),
        ),
    ]
