# Generated by Django 5.1.2 on 2024-11-16 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0011_revenue_roomrevenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_core.student_account'),
            preserve_default=False,
        ),
    ]
