# Generated by Django 5.1.2 on 2024-11-18 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0012_rent_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenue',
            name='electric',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='revenue',
            name='service',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='revenue',
            name='water',
            field=models.IntegerField(default=0),
        ),
    ]
