# Generated by Django 5.1.2 on 2024-11-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0013_revenue_electric_revenue_service_revenue_water'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenue',
            name='rentroom',
            field=models.IntegerField(default=0),
        ),
    ]
